config/routes.rb
FooFoo::Application.routes.draw do
  resources :foo_models

end

app/models/foo_model.rb
class FooModel < ActiveRecord::Base
  attr_accessible :name
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/foo_models_controller.rb
class FooModelsController < ApplicationController
  # GET /foo_models
  # GET /foo_models.json
  def index
    @foo_models = FooModel.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @foo_models }
    end
  end

  # GET /foo_models/1
  # GET /foo_models/1.json
  def show
    @foo_model = FooModel.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @foo_model }
    end
  end

  # GET /foo_models/new
  # GET /foo_models/new.json
  def new
    @foo_model = FooModel.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @foo_model }
    end
  end

  # GET /foo_models/1/edit
  def edit
    @foo_model = FooModel.find(params[:id])
  end

  # POST /foo_models
  # POST /foo_models.json
  def create
    @foo_model = FooModel.new(params[:foo_model])

    respond_to do |format|
      if @foo_model.save
        format.html { redirect_to @foo_model, notice: 'Foo model was successfully created.' }
        format.json { render json: @foo_model, status: :created, location: @foo_model }
      else
        format.html { render action: "new" }
        format.json { render json: @foo_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /foo_models/1
  # PUT /foo_models/1.json
  def update
    @foo_model = FooModel.find(params[:id])

    respond_to do |format|
      if @foo_model.update_attributes(params[:foo_model])
        format.html { redirect_to @foo_model, notice: 'Foo model was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @foo_model.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /foo_models/1
  # DELETE /foo_models/1.json
  def destroy
    @foo_model = FooModel.find(params[:id])
    @foo_model.destroy

    respond_to do |format|
      format.html { redirect_to foo_models_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foo_models_helper.rb
module FooModelsHelper
end

app/views/foo_models/_form.html.erb
<%= form_for(@foo_model) do |f| %>
  <% if @foo_model.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foo_model.errors.count, "error") %> prohibited this foo_model from being saved:</h2>

      <ul>
      <% @foo_model.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foo_models/edit.html.erb
<h1>Editing foo_model</h1>

<%= render 'form' %>

<%= link_to 'Show', @foo_model %> |
<%= link_to 'Back', foo_models_path %>

app/views/foo_models/index.html.erb
<h1>Listing foo_models</h1>

<table>
  <tr>
    <th>Name</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @foo_models.each do |foo_model| %>
  <tr>
    <td><%= foo_model.name %></td>
    <td><%= link_to 'Show', foo_model %></td>
    <td><%= link_to 'Edit', edit_foo_model_path(foo_model) %></td>
    <td><%= link_to 'Destroy', foo_model, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foo model', new_foo_model_path %>

app/views/foo_models/new.html.erb
<h1>New foo_model</h1>

<%= render 'form' %>

<%= link_to 'Back', foo_models_path %>

app/views/foo_models/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @foo_model.name %>
</p>


<%= link_to 'Edit', edit_foo_model_path(@foo_model) %> |
<%= link_to 'Back', foo_models_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FooFoo</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>